services:
  database:
     image: postgres
     ports: 
       - 5001:5432
     volumes:
      - pgdata:/var/lib/postgresql/data
     environment: 
      - POOSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Aaka$h1234
      - POSTGRES_DB=crudapi
volumes:
  pgdata:
   


